### ISSUE TITLE
Undo `--deselect` additions to `pyproject.toml`

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#117]
We [recently excluded two more tests](https://github.com/conda/conda-libmamba-solver/pull/101) in `pyproject.toml`:

```toml
  # TEMPORARY! FIXME - only skipping to ease development in other PRs, revert ASAP
  # We need conda-forge to release a new Python 3.8.x that defaults has,
  # but a bug in conda-build is preventing feedstocks from operating correctly.
  "--deselect=tests/test_priority.py::PriorityIntegrationTests::test_channel_order_channel_priority_true",
  # Known 23.1.0 breakage - investigated by costrouc
  "--deselect=tests/gateways/test_connection.py::test_s3_server",
```

This is a reminder to re-enable them whenever possible.
